import { StyleSheet } from 'react-native';
import { theme } from '../../../theme/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        padding: theme.spacing.lg,
        paddingBottom: theme.spacing.lg + theme.spacing.xl,
        backgroundColor: theme.colors.background,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
        color: theme.colors.text,
    },
    subtitle: {
        fontSize: 16,
        textAlign: 'center',
        color: theme.colors.textSecondary,
        marginBottom: 30,
    },
    waitingContainer: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
        backgroundColor: theme.colors.background,
    },
    loadingBox: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    waitingTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginTop: 20,
        marginBottom: 5,
    },
    waitingSubtitle: {
        fontSize: 18,
        color: theme.colors.activityIndicator,
        fontWeight: '500',
        marginBottom: 20,
    },
    waitingMessage: {
        fontSize: 16,
        textAlign: 'center',
        color: theme.colors.textSecondary,
        paddingHorizontal: 20,
        lineHeight: 24,
    },
    disconnectContainer: {
        paddingBottom: 40,
    },
    matchTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.colors.activityIndicator,
        marginBottom: 20,
        textAlign: 'center',
    },
    matchCard: {
        backgroundColor: theme.colors.cardBackground,
        padding: 20,
        borderRadius: 12,
        width: '100%',
        alignItems: 'center',
        marginBottom: 15,
        borderWidth: 1,
        borderColor: theme.colors.cardInactiveBorder,
    },
    playerText: {
        fontSize: 22,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginVertical: 10,
        textAlign: 'center',
    },
    vsText: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        fontWeight: 'bold',
    },
    configCard: {
        backgroundColor: theme.colors.cardBackground,
        padding: 15,
        borderRadius: 12,
        width: '100%',
        alignItems: 'center',
    },
    configText: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        marginVertical: 5,
    },
    errorText: {
        fontSize: theme.typography.sizes.sm,
        fontFamily: theme.typography.fontFamily.semiBold,
        color: theme.colors.textError,
        marginBottom: theme.spacing.lg,
    },

    suspensionOverlay: {
        ...StyleSheet.absoluteFill,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        zIndex: 1000,
        elevation: 20,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
    },
    suspensionCard: {
        backgroundColor: theme.colors.toastBackground,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: theme.colors.toastBorderError,
        padding: 32,
        alignItems: 'center',
        width: '100%',
        shadowColor: theme.colors.toastBorderError,
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 10,
    },
    suspensionIcon: {
        fontSize: 52,
        marginBottom: 16,
    },
    suspensionTitle: {
        color: theme.colors.toastText,
        fontFamily: theme.typography.fontFamily.bold,
        fontSize: theme.typography.sizes.lg,
        textAlign: 'center',
        marginBottom: 12,
    },
    suspensionSubtitle: {
        color: theme.colors.toastTextSecondary,
        fontFamily: theme.typography.fontFamily.regular,
        fontSize: theme.typography.sizes.sm,
        textAlign: 'center',
        lineHeight: 22,
    },
    suspensionButton: {
        marginTop: 24,
    },
});
